### ISSUE TITLE
 Nfsuclient Не является приложением win32 при запуске на windows xp

### ISSUE THREAD

**Issue by nikita-stepanov** [HarpyWar/nfsuserver#1]
Windows xp у меня на virtualbox если что.
You can translate this in English

**Comment by HarpyWar** [comment]
Клиент скомпилирован без поддержки Windows XP. 
Можно установить на XP старую Visual Studio (вместе с VC++), например 2010 https://visualstudio.microsoft.com/ru/vs/older-downloads. Открыть `nfsuclient/client2.vcproj`, правой кнопкой на проект > Build, и соберется рабочая версия клиента.
