### ISSUE TITLE
Unable to configure hosts file on Windows 11

### ISSUE THREAD

**Issue by sametkrt** [HarpyWar/nfsuserver#17]
Issue:
![Screenshot 2024-11-01 180845](https://github.com/user-attachments/assets/f42e8b18-47fc-4569-919f-cc9c25f85053)

How to fix this issue?

Can anyone please share how hosts file look like for a given server?

**Comment by sametkrt** [comment]
@Pelorojo @HarpyWar @ian-travers

**Comment by sametkrt** [comment]
@Pelorojo @HarpyWar @ian-travers @NicknineTheEagle

**Comment by NicknineTheEagle** [comment]
Did you seriously just blindly ping everyone whose name you saw in the repository? Have you got no manners?

**Comment by Pelorojo** [comment]
@sametkrt hosts file is located at %windir%\system32\drivers\etc and the line for nfsuclient always looks like
`ps2nfs04.ea.com 127.0.0.1`
to fix the problem there are several solutions:
a) you edit the hosts file yourself by adding this line and ignore this warning
b) you start nfsuclient as administrator so it can edit the hosts file for you without any warnings
c) use kickstart netplay launcher instead -> http://nfsa.ca/f7903

**Comment by sametkrt** [comment]
Cool this works thanks a lot @Pelorojo 

Note: hosts file cannot be overridden even when you run the app with admin privileges.
