### ISSUE TITLE
Troubles with nfsu.ini file

### ISSUE THREAD

**Issue by MrAroGH** [HarpyWar/nfsuserver#2]
Looks like nfsuserver2.exe completely ignores this file. I tried to change "servername", "enablelogfile", etc. attributes, but the server is completely don't care about this, the server name is set by default, logfile is created and used. I also tried to delete it, same result. How to fix that?

**Comment by HarpyWar** [comment]
Download fixed `nfsuserver.1.0.3.win32.zip`
