### ISSUE TITLE
Interopility with other games.

### ISSUE THREAD

**Issue by VTSTech** [HarpyWar/nfsuserver#4]
Not really an issue.

Just wanted to report that this worked beautifully in Burnout 3 for PS2. Was trying to figure out how to get past the first few connection messages and this just does a whole bunch of them.

User Reg/Account & Persona Creation worked.

<img src="https://i.gyazo.com/d185eab9359ca179a0e56e90dda692b3.png">

**Comment by HarpyWar** [comment]
Nice, it looks like old EA games have the same authentication mechanism, and it requires to research game packets to add support for more games.

**Comment by VTSTech** [comment]
One thing I noticed.

nfsuserver2.cpp

tmp=strstr(buf+17, "VERS=\"");

Other titles do not have a " on that value. Been slowly modifying this to work with Burnout.

/*
auth
VERS=FLM/A1
SKU=FLAME
SLUS=SLUS-FLAME
LANG=en
FROM=uk
MID=$766d61638759
NAME=zzzz
PASS="~z#;_HpF8NC&3>K\A3+5*Pw ecI2JkD"
TOS=1
*/

	//localsin.sin_port = htons(10900); // ps2nfs04.ea.com Need for Speed Underground
	//localsin.sin_port = htons(21800); // ps2burnout05.ea.com Burnout 3 PAL Retail
	//localsin.sin_port = htons(21801); // ps2burnout05.ea.com Burnout 3 NTSC Retail
	localsin.sin_port = htons(21840); // ps2lobby02.beta.ea.com Burnout 3 PAL Review
	//localsin.sin_port = htons(21870); // ps3burnout08.ea.com Burnout Paradise
